import { CourseMode, OrderStatus, PaymentProvider, PaymentStatus, Prisma, ProductType } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { HttpError, centsToMoney, clearSession, fulfillOrder, getSession, hashPassword, initializePayment, moneyToCents, prisma, requireAdmin, requireSession, setSession, verifyPassword } from "@/lib/server";

type Ctx = { params: Promise<{ path?: string[] }> };
const json = (data: unknown, status = 200) => NextResponse.json(data, { status });
const register = z.object({ name: z.string().trim().min(2).max(100), email: z.string().trim().email().transform(v => v.toLowerCase()), phone: z.string().trim().min(6).max(30).optional(), password: z.string().min(8).max(100), departmentId: z.string().cuid().optional() });
const login = z.object({ email: z.string().trim().email().transform(v => v.toLowerCase()), password: z.string().min(1) });
const courseInput = z.object({ title: z.string().trim().min(2).max(200), slug: z.string().trim().min(2).max(200), description: z.string().trim().max(10000).optional(), mode: z.enum(["LIVE", "RECORDED"]), price: z.coerce.number().min(0), published: z.boolean().default(false), departmentId: z.string().cuid().optional(), semesterId: z.string().cuid().optional() });
const productInput = z.object({ name: z.string().trim().min(2).max(200), slug: z.string().trim().min(2).max(200), description: z.string().trim().max(10000).optional(), type: z.enum(["BOOK", "DIGITAL"]), price: z.coerce.number().min(0), stock: z.coerce.number().int().min(0).nullable().optional(), isActive: z.boolean().default(true) });
const checkout = z.object({ items: z.array(z.object({ courseId: z.string().cuid().optional(), productId: z.string().cuid().optional(), quantity: z.coerce.number().int().min(1).max(20).default(1) })).min(1).max(50), provider: z.enum(["BKASH", "NAGAD", "SSLCOMMERZ", "MANUAL"]).default("MANUAL"), shipping: z.object({ name: z.string().min(2), phone: z.string().min(6), address: z.string().min(5), city: z.string().min(2), postalCode: z.string().optional() }).optional() }).superRefine((v,c)=>v.items.forEach((x,i)=>{ if(Boolean(x.courseId)===Boolean(x.productId)) c.addIssue({code:z.ZodIssueCode.custom,path:["items",i],message:"Each item needs exactly one courseId or productId"}); if(x.courseId&&x.quantity!==1)c.addIssue({code:z.ZodIssueCode.custom,path:["items",i,"quantity"],message:"A course can only be purchased once"}) }));
const progress = z.object({ completed: z.boolean().default(true) });
const webhook = z.object({ orderId: z.string().cuid(), status: z.enum(["PAID","FAILED","CANCELLED"]), providerReference: z.string().max(200).optional() });

function userView(u:any){return {id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role};}
function courseView(c:any){return {id:c.id,title:c.title,slug:c.slug,description:c.description,mode:c.mode,price:c.price.toString(),published:c.published,department:c.department?{id:c.department.id,code:c.department.code,name:c.department.name}:null,semester:c.semester?{id:c.semester.id,number:c.semester.number,label:c.semester.label}:null,lessonsCount:c._count?.lessons,createdAt:c.createdAt,updatedAt:c.updatedAt};}
function productView(p:any){return {id:p.id,name:p.name,slug:p.slug,description:p.description,type:p.type,price:p.price.toString(),stock:p.stock,isActive:p.isActive,createdAt:p.createdAt,updatedAt:p.updatedAt};}
function orderView(o:any){return {id:o.id,status:o.status,paymentStatus:o.paymentStatus,paymentProvider:o.paymentProvider,paymentRef:o.paymentRef,subtotal:o.subtotal.toString(),discount:o.discount.toString(),total:o.total.toString(),shippingAddress:o.shippingAddress,user:o.user?userView(o.user):undefined,items:o.items?.map((i:any)=>({id:i.id,title:i.title,quantity:i.quantity,unitPrice:i.unitPrice.toString(),productId:i.productId,courseId:i.courseId})),createdAt:o.createdAt,updatedAt:o.updatedAt};}
async function pathOf(ctx:Ctx){return (await ctx.params).path??[];}

async function GET(request:Request,ctx:Ctx){
 const path=await pathOf(ctx); const url=new URL(request.url);
 if(path.length===0||path[0]==="health") return json({ok:true,service:"shohoj-porashuna-api",timestamp:new Date().toISOString()});
 if(path[0]==="me"&&path.length===1){const s=await requireSession();const u=await prisma.user.findUnique({where:{id:s.id}});if(!u)throw new HttpError(404,"User not found");return json({user:userView(u)});}
 if(path[0]==="me"&&path[1]==="dashboard"){const s=await requireSession();const enrollments=await prisma.enrollment.findMany({where:{userId:s.id},include:{course:{include:{lessons:{select:{id:true}}}}},orderBy:{enrolledAt:"desc"}});const ids=enrollments.flatMap(e=>e.course.lessons.map(l=>l.id));const done=ids.length?await prisma.lessonProgress.findMany({where:{userId:s.id,lessonId:{in:ids},completedAt:{not:null}},select:{lessonId:true}}):[];const doneSet=new Set(done.map(x=>x.lessonId));const orders=await prisma.order.findMany({where:{userId:s.id},include:{items:true},orderBy:{createdAt:"desc"},take:20});return json({user:s,enrollments:enrollments.map(e=>({id:e.id,status:e.status,enrolledAt:e.enrolledAt,course:courseView(e.course),lessonsTotal:e.course.lessons.length,lessonsCompleted:e.course.lessons.filter(l=>doneSet.has(l.id)).length})),orders:orders.map(orderView)});}
 if(path[0]==="courses"&&path.length===1){const s=await getSession();const where:Prisma.CourseWhereInput=s?.role==="ADMIN"?{}:{published:true};const q=url.searchParams.get("q")?.trim();if(q)where.OR=[{title:{contains:q,mode:"insensitive"}},{description:{contains:q,mode:"insensitive"}}];const [data,total]=await prisma.$transaction([prisma.course.findMany({where,include:{department:true,semester:true,_count:{select:{lessons:true,enrollments:true}}},orderBy:{createdAt:"desc"}}),prisma.course.count({where})]);return json({data:data.map(courseView),pagination:{total,pageCount:Math.ceil(total/20)}});}
 if(path[0]==="courses"&&path.length===2){const c=await prisma.course.findFirst({where:{OR:[{id:path[1]},{slug:path[1]}]},include:{department:true,semester:true,lessons:{orderBy:{sortOrder:"asc"}}}});if(!c)throw new HttpError(404,"Course not found");const s=await getSession();if(!c.published&&s?.role!=="ADMIN")throw new HttpError(404,"Course not found");const enrollment=s?await prisma.enrollment.findUnique({where:{userId_courseId:{userId:s.id,courseId:c.id}}}):null;const access=s?.role==="ADMIN"||Boolean(enrollment);return json({course:courseView(c),enrolled:Boolean(enrollment),lessons:c.lessons.map(l=>({id:l.id,title:l.title,slug:l.slug,description:l.description,sortOrder:l.sortOrder,durationMin:l.durationMin,isPreview:l.isPreview,locked:!l.isPreview&&!access,videoUrl:l.isPreview||access?l.videoUrl:null,content:l.isPreview||access?l.content:null}))});}
 if(path[0]==="products"&&path.length===1){const ps=await prisma.product.findMany({where:{isActive:true},orderBy:{createdAt:"desc"}});return json({data:ps.map(productView)});}
 if(path[0]==="admin"&&path[1]==="orders"){await requireAdmin();const os=await prisma.order.findMany({include:{user:{select:{id:true,name:true,email:true,phone:true}},items:true},orderBy:{createdAt:"desc"},take:100});return json({data:os.map(orderView)});}
 throw new HttpError(404,"Endpoint not found");
}

async function POST(request:Request,ctx:Ctx){
 const path=await pathOf(ctx);
 if(path[0]==="auth"&&path[1]==="register"){const i=register.parse(await request.json());if(await prisma.user.findUnique({where:{email:i.email}}))throw new HttpError(409,"An account already exists for this email");if(i.phone&&await prisma.user.findUnique({where:{phone:i.phone}}))throw new HttpError(409,"An account already exists for this phone"));const u=await prisma.user.create({data:{name:i.name,email:i.email,phone:i.phone,passwordHash:await hashPassword(i.password),departmentId:i.departmentId}});return setSession(json({user:userView(u)},201),{id:u.id,name:u.name,email:u.email,role:u.role});}
 if(path[0]==="auth"&&path[1]==="login"){const i=login.parse(await request.json());const u=await prisma.user.findUnique({where:{email:i.email}});if(!u||!(await verifyPassword(i.password,u.passwordHash)))throw new HttpError(401,"Invalid email or password");return setSession(json({user:userView(u)}),{id:u.id,name:u.name,email:u.email,role:u.role});}
 if(path[0]==="auth"&&path[1]==="logout")return clearSession(json({ok:true}));
 if(path[0]==="admin"&&path[1]==="courses"){await requireAdmin();const i=courseInput.parse(await request.json());const c=await prisma.course.create({data:{...i,mode:i.mode as CourseMode,price:i.price.toFixed(2)},include:{department:true,semester:true,_count:{select:{lessons:true,enrollments:true}}}});return json({course:courseView(c)},201);}
 if(path[0]==="admin"&&path[1]==="products"){await requireAdmin();const i=productInput.parse(await request.json());const p=await prisma.product.create({data:{...i,type:i.type as ProductType,price:i.price.toFixed(2)}});return json({product:productView(p)},201);}
 if(path[0]==="courses"&&path.length===3&&path[2]==="enroll"){const s=await requireSession();const c=await prisma.course.findFirst({where:{OR:[{id:path[1]},{slug:path[1]}],published:true}});if(!c)throw new HttpError(404,"Course not found");if(Number(c.price)>0)throw new HttpError(402,"This course requires payment",{courseId:c.id,price:c.price.toString()});const e=await prisma.enrollment.upsert({where:{userId_courseId:{userId:s.id,courseId:c.id}},create:{userId:s.id,courseId:c.id},update:{status:"ACTIVE"}});return json({enrollment:e},201);}
 if(path[0]==="lessons"&&path.length===3&&path[2]==="complete"){const s=await requireSession();const i=progress.parse(await request.json().catch(()=>({})));const l=await prisma.lesson.findUnique({where:{id:path[1]}});if(!l)throw new HttpError(404,"Lesson not found");if(s.role!=="ADMIN"){const e=await prisma.enrollment.findUnique({where:{userId_courseId:{userId:s.id,courseId:l.courseId}}});if(!e||e.status==="CANCELLED")throw new HttpError(403,"Enroll in the course to track progress");}const p=await prisma.lessonProgress.upsert({where:{userId_lessonId:{userId:s.id,lessonId:l.id}},create:{userId:s.id,lessonId:l.id,completedAt:i.completed?new Date():null},update:{completedAt:i.completed?new Date():null}});return json({progress:p});}
 if(path[0]==="checkout"&&path.length===1){const s=await requireSession();const i=checkout.parse(await request.json());const courses=await prisma.course.findMany({where:{id:{in:i.items.flatMap(x=>x.courseId?[x.courseId]:[])},published:true}});const products=await prisma.product.findMany({where:{id:{in:i.items.flatMap(x=>x.productId?[x.productId]:[])},isActive:true}});const cm=new Map(courses.map(x=>[x.id,x])),pm=new Map(products.map(x=>[x.id,x]));const lines=i.items.map(x=>{if(x.courseId){const c=cm.get(x.courseId);if(!c)throw new HttpError(404,"Course not found");return {courseId:c.id,title:c.title,unitPriceCents:moneyToCents(c.price),quantity:1,shipping:false};}const p=pm.get(x.productId!);if(!p)throw new HttpError(404,"Product not found");if(p.stock!==null&&p.stock<x.quantity)throw new HttpError(409,"Insufficient stock");return {productId:p.id,title:p.name,unitPriceCents:moneyToCents(p.price),quantity:x.quantity,shipping:p.type===ProductType.BOOK};});if(lines.some(x=>x.shipping)&&!i.shipping)throw new HttpError(400,"Shipping details are required for books");const subtotal=lines.reduce((n,x)=>n+x.unitPriceCents*x.quantity,0);const order=await prisma.order.create({data:{userId:s.id,status:OrderStatus.PENDING,paymentStatus:PaymentStatus.PENDING,paymentProvider:i.provider as PaymentProvider,subtotal:centsToMoney(subtotal),discount:"0.00",total:centsToMoney(subtotal),shippingAddress:i.shipping,items:{create:lines.map(x=>({title:x.title,quantity:x.quantity,unitPrice:centsToMoney(x.unitPriceCents),courseId:x.courseId,productId:x.productId}))}},include:{items:true}});const payment=await initializePayment({provider:i.provider as PaymentProvider,orderId:order.id,amount:centsToMoney(subtotal)});return json({order:orderView(order),payment},201);}
 if(path[0]==="payments"&&path[1]==="webhook"){if(!process.env.PAYMENT_WEBHOOK_SECRET||request.headers.get("x-payment-webhook-secret")!==process.env.PAYMENT_WEBHOOK_SECRET)throw new HttpError(401,"Invalid webhook credentials");const i=webhook.parse(await request.json());if(i.status==="PAID"){const o=await fulfillOrder(i.orderId);if(i.providerReference)await prisma.order.update({where:{id:i.orderId},data:{paymentRef:i.providerReference}});return json({ok:true,orderId:o.id,status:o.status});}const o=await prisma.order.update({where:{id:i.orderId},data:{status:i.status==="FAILED"?"FAILED":"CANCELLED",paymentStatus:i.status==="FAILED"?"FAILED":"CANCELLED",paymentRef:i.providerReference}});return json({ok:true,orderId:o.id,status:o.status});}
 if(path[0]==="admin"&&path[1]==="orders"&&path[3]==="mark-paid"){await requireAdmin();const o=await fulfillOrder(path[2]);return json({orderId:o.id,status:o.status,paymentStatus:o.paymentStatus});}
 throw new HttpError(404,"Endpoint not found");
}

async function run(fn:()=>Promise<NextResponse>){try{return await fn();}catch(e){if(e instanceof HttpError)return json({error:e.message,details:e.details},e.status);if(e instanceof z.ZodError)return json({error:"Validation failed",details:e.flatten()},400);if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002")return json({error:"A record with this unique value already exists"},409);console.error(e);return json({error:"Internal server error"},500);}}
export async function GET(request:Request,ctx:Ctx){return run(()=>GET(request,ctx));}
export async function POST(request:Request,ctx:Ctx){return run(()=>POST(request,ctx));}